// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Request = { "type": "GetPrinters" } | { "type": "GetDefaultPrinter" } | { "type": "GetPrinter", name: string, } | { "type": "PrintRaw", name: string, data: string, };
