// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Response = { error: string, } | { printers: Array<string>, } | { id: bigint, } | { printer: { name: string, data_type: string, description: string, is_default: boolean, state: string, }, };
